### ISSUE TITLE
CID Procedimientos que se puedan importar imagenes en QuillJS

### ISSUE THREAD

**Issue by guivaloz** [PJECZ/pjecz-plataforma-web#129]
Nos gustaria un comentario que recomendara editar las imágenes antes de subirlas. Para que no queden demasiado grandes.

**Comment by aranda90** [comment]
Se va a eliminar este issues y se va a crear otro para acomodar el PDF las imágenes se queden alineadas a donde se pusieron.

**Comment by guivaloz** [comment]
Cierro este issue.
