### ISSUE TITLE
Entidad de Género: comenzar blueprint

### ISSUE THREAD

**Issue by ricval** [PJECZ/pjecz-plataforma-web#181]
Implementación de un nuevo _blueprint_ para migrar la tabla de **entidad de Género**. Haciendo una sección administrativa y otra pública para la consulta en el sitio.

**Comment by guivaloz** [comment]
Campos en la tabla entidades_generos:

- _id_
- nombre_anterior
- nombre_actual
- genero_anterior
- genero_actual
- procedimiento
- nacimiento_fecha
- nacimiento_lugar
- padre
- madre
- _estatus_
- _creado_
- _modificado_
