### ISSUE TITLE
Crear nuevos blueprints para el sistema administrativo de citas

### ISSUE THREAD

**Issue by ricval** [PJECZ/pjecz-plataforma-web#287]
Tabla para clientes 'clientes':
| llave | nombre |
| --- | --- |
| pk | id
| | nombres
| | apellido_paterno
| | apellido_materno
| U | curp
| FK | domicilio_id
| | telefono_celular
| | email
| | contrasena_cifrada
| | hash
| | renovacion_fecha
| | creado*
| | estatus*

**Comment by guivaloz** [comment]
Cierro este issue para crear issues por cada tarea a realizar.
