### ISSUE TITLE
Citas v2: crear blueprint cit_servicios

### ISSUE THREAD

**Issue by guivaloz** [PJECZ/pjecz-plataforma-web#295]
Los administradores deben de poder crear, editar, eliminar y recuperar los servicios del sistema de citas.

**Comment by ricval** [comment]
La tabla quedó:

| llave | nombre | tipo |
| --- | --- | --- |
| PK | id | int |
| U | clave | str |
| | nombre | str |
| | solicitar_expedientes | bool |
| | duracion | int |

**Comment by ricval** [comment]
Como validaciones coloque:
  - Clave repetida, advertencia
  - Mínimo de duración: 15 minutos
  - Máximo de duración: 08:00 horas
