### ISSUE TITLE
Citas v2: crear blueprint cit_citas

### ISSUE THREAD

**Issue by guivaloz** [PJECZ/pjecz-plataforma-web#296]
Los ragistros nuevos vienen del sistema de citas. Aqui el juzgado/oficilia puede ver el listado de citas, detalles y editar algunas cosas.

**Comment by ricval** [comment]
La tabla quedaría así:
| llave | nombre | tipo |
| --- | --- | --- |
| PK | id | int |
| FK | servicio_id | int |
| FK | cliente_id | int |
| FK | oficina_id | int |
| | inicio_tiempo | datetime |
| | termino_tiempo | datetime |
| | notas | text |
| | estado | enum |


estado valores:
* Asistió
* Canceló
* Confirmó
* Pendiente
