### ISSUE TITLE
Citas V2 - Oficinas: Crear blueprint

### ISSUE THREAD

**Issue by guivaloz** [PJECZ/pjecz-plataforma-web#297]
Oficinas brindara informacion al sistema de citas. Los adminisradores seran los unicos con capacidad de crear y editar informacion aqui.

**Comment by ricval** [comment]
Esta tabla se encuentra tanto en Soportes como en Citas.
Hago la tabla y la ligamos desde cit_oficinas

**Comment by ricval** [comment]
Se encontraba duplicada con el issue #310, yo me encargo de este blueprint

**Comment by ricval** [comment]
La tabla quedaría así:
| llave | nombre | tipo |
| --- | --- | --- |
| PK | id | int |
| FK | distrito_id | int |
| FK | domicilio_id | int |
| U | clave | str |
| | descripcion | str |
| | es_juridiccional | bool |
| | apertura | time |
| | cierre | time |
| | limite_personas | int |

**Comment by ricval** [comment]
Closes #313
