### ISSUE TITLE
Soportes Tickets: Al tomar un ticket abierto que ya esta categorizado se pierde la categoria.

### ISSUE THREAD

**Issue by guivaloz** [PJECZ/pjecz-plataforma-web#352]

**Comment by guivaloz** [comment]
![Screenshot_20220216_092002](https://user-images.githubusercontent.com/1296621/154296192-0be5f250-7e9d-4b75-921e-7d96c30f8577.png)
![Screenshot_20220216_092018](https://user-images.githubusercontent.com/1296621/154296199-e0e9ea7e-ce55-45fb-82cf-c101d6e26574.png)

**Comment by ricval** [comment]
Enterado, lo reviso
